# Generated by Django 4.1.7 on 2023-06-29 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_viewedarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleadmin',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
