# Generated by Django 4.1.7 on 2023-06-26 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionLikesDislikes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comment', models.CharField(max_length=255)),
                ('likes', models.IntegerField()),
                ('dislikes', models.IntegerField()),
            ],
            options={
                'db_table': 'discussion_likes_dislikes',
                'managed': False,
            },
        ),
    ]
